config/routes.rb
Fb::Application.routes.draw do
      
    devise_for :users

    resources :boards do
    resources :posts
  end

  namespace :admin do 
    resources :boards do
      resources :posts 
    end
  end
  

root :to => "boards#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :board
  belongs_to :user
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'
  
  before_filter :find_board
  before_filter :authenticate_user! , :except => [ :index ]
  
  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @board = Board.find(params[:board_id])
    @post = Post.find(params[:id])
    
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(board_post_path(@board,@post), :notice => 'Post was successfully updated.') }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @board = Board.find(params[:board_id])
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(board_posts_path(@board)) }
      format.json { head :ok }
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :authenticate_user! , :except => [ :show, :index ]
  
  # GET /posts
  # GET /posts.json
  def index
    @board = Board.find(params[:board_id])
    redirect_to board_path(@board)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @board = Board.find(params[:board_id])
    @post = @board.posts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @board = Board.find(params[:board_id])
    @post = @board.posts.build
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = current_user.posts.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @board = Board.find(params[:board_id])
    @post = @board.posts.build(params[:post])
    @post.user_id = current_user.id
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to(board_posts_path (@board), :notice => 'Post was successfully updated.') }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @board = Board.find(params[:board_id])
    @post = current_user.posts.find(params[:id])
    
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(board_post_path(@board,@post), :notice => 'Post was successfully updated.') }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @board = Board.find(params[:board_id])
    #@post = @board.posts.find(params[:id])
    @post = current_user.posts.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(board_posts_path(@board)) }
      format.json { head :ok }
    end
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/admin/posts/edit.html.erb
<h1>Editing post</h1>
<%= form_for @post, :url => admin_board_post_path(@board,@post) do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<% end %>
<%= link_to 'Show', board_post_path(@board,@post) %> |
<%= link_to 'Back', board_posts_path(@board) %>

app/views/admin/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>