config/routes.rb
Fb::Application.routes.draw do
      
    devise_for :users

    resources :boards do
    resources :posts
  end

  namespace :admin do 
    resources :boards do
      resources :posts 
    end
  end
  

root :to => "boards#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :posts
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < ApplicationController
  layout 'admin'  
  before_filter :require_is_admin
  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @boards }
    end
  end



  # GET /boards/new
  # GET /boards/new.json
  def new
    @board = Board.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to(board_path(@board), :notice => 'Board was successfully created.') }
        format.json { render :json => @board, :status => :created, :location => @board }
      else
        format.html { render :action => "new" }
        format.json { render :json => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.json
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to(board_path(@board), :notice => 'Board was successfully updated.') }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to(admin_boards_url) }
      format.json { head :ok }
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @board = Board.find(params[:id])
    @posts = @board.posts
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @board }
    end
  end

  # # GET /boards/new
  # # GET /boards/new.json
  # def new
    # @board = Board.new
# 
    # respond_to do |format|
      # format.html # new.html.erb
      # format.json { render :json => @board }
    # end
  # end
# 
  # # GET /boards/1/edit
  # def edit
    # @board = Board.find(params[:id])
  # end
# 
  # # POST /boards
  # # POST /boards.json
  # def create
    # @board = Board.new(params[:board])
# 
    # respond_to do |format|
      # if @board.save
        # format.html { redirect_to @board, :notice => 'Board was successfully created.' }
        # format.json { render :json => @board, :status => :created, :location => @board }
      # else
        # format.html { render :action => "new" }
        # format.json { render :json => @board.errors, :status => :unprocessable_entity }
      # end
    # end
  # end
# 
  # # PUT /boards/1
  # # PUT /boards/1.json
  # def update
    # @board = Board.find(params[:id])
# 
    # respond_to do |format|
      # if @board.update_attributes(params[:board])
        # format.html { redirect_to @board, :notice => 'Board was successfully updated.' }
        # format.json { head :ok }
      # else
        # format.html { render :action => "edit" }
        # format.json { render :json => @board.errors, :status => :unprocessable_entity }
      # end
    # end
  # end
# 
  # # DELETE /boards/1
  # # DELETE /boards/1.json
  # def destroy
    # @board = Board.find(params[:id])
    # @board.destroy
# 
    # respond_to do |format|
      # format.html { redirect_to boards_url }
      # format.json { head :ok }
    # end
  # end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/index.html.erb
<h1>Listing boards</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boards.each do |board| %>
  <tr>
    <td><%= board.name %></td>
    <td><%= link_to 'Show', board %></td>
   <% if current_user && current_user.is_admin? %>
   	<td><%= link_to 'A-Edit', edit_admin_board_path(board) %></td>
   	<td><%= link_to 'A-Destroy', admin_boards_path , :confirm => 'Are you sure?', :method => :delete %></td>
   <% end %> 
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Board', new_board_path %>
<% if current_user && current_user.is_admin? %>
	<%= link_to 'A-New Board', new_admin_board_path %>
<% end %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @board.name %>
</p>

<h1>Listing posts</h1>
<table>
	<tr>
		<th>Title</th>
		<th>Content</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<% @posts.each do |post|%>
	<tr>
		<td><%= post.title%></td>
		<td><%= post.content %></td>
		<td><%= link_to 'Show', board_post_path(@board,post) %></td>
		<% if current_user && post.user == current_user %>
			<td><%= link_to 'Edit', edit_board_post_path(@board,post) %></td>
			<td><%= link_to 'Destroy', board_post_path (@board,post), :confirm => 'Are you sure?', :method => :delete %></td>
		<% end %>
		
		<% if current_user && current_user.is_admin? %>
      		<td><%= link_to 'A-Edit', edit_admin_board_post_path(@board,post) %></td>
      		<td><%= link_to 'A-Destroy', admin_board_post_path(@board,post), :confirm => 'Are you sure?', :method => :delete %></td>
   		<% end %>
	</tr>	
	<% end %>
</table>

<br />

<%= link_to 'New Post', new_board_post_path(@board) %> |
<% if current_user && current_user.is_admin? %>
	<%= link_to 'A-Edit', edit_admin_board_path(@board) %> |
<% end %>
<%= link_to 'Back', boards_path %>